### ISSUE TITLE
Not working on Ubuntu 16.04

### ISSUE THREAD

**Issue by erwan35** [dagargo/microdude#1]
Hello,

I know that this Ubuntu release is getting old but I'm getting this :

`erwan@menhir:~$ microdude
Traceback (most recent call last):
  File "/usr/local/bin/microdude", line 3, in <module>
    from microdude.editor import Editor
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/usr/local/lib/python3.5/dist-packages/MicroDude-1.3-py3.5.egg/microdude/editor.py", line 66, in <module>
GLib.Error: gtk-builder-error-quark: /home/erwan/.python-eggs/MicroDude-1.3-py3.5.egg-tmp/microdude/resources/gui.glade:24:1 Required gtk+ version 3.20, current version is 3.18 (7)`

Do you think that It should be feasible to have it working on this release ?

I will be upgrading soon :)

Cheers
Erwan

**Comment by dagargo** [comment]
Hi, Erwan.

I suggest you to checkout the 1.2.1 tag, which uses gtk+ version 3.12.

If you feel more adventurous you could try to change the following line in the glade file and see if it works for you.
```
<requires lib="gtk+" version="3.20"/>
```

Cheers

**Comment by erwan35** [comment]
Hello,

You are my hero !

I have changed the glade file and at least I'm able to change the parameters I wanted to change ! (play on : note on and load/save the sequences).

I have to play around with the MB (I bought it this week) and your software to see if I have some problems.

1000 Thanks
Erwan

**Comment by dagargo** [comment]
I'm glad it worked.

Since the gtk+ 3.18 version and Ubuntu 16.04 are quite old I consider it is not a good idea to change this now.
