### ISSUE TITLE
 Direct access through the connector class not working

### ISSUE THREAD

**Issue by erwan35** [dagargo/microdude#2]
Hello,

I have tried to use the connector class without success:

```
erwan@menhir:~$ python3
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from microdude import connector
>>> connector.get_ports()
['MicroBrute:MicroBrute MIDI 1 44:0', 'MicroBrute:MicroBrute MIDI 2 44:1', 'Midi Through:Midi Through Port-0 14:0', 'Midi Through:Midi Through Port-1 14:1', 'Midi Through:Midi Through Port-10 14:10', 'Midi Through:Midi Through Port-11 14:11', 'Midi Through:Midi Through Port-12 14:12', 'Midi Through:Midi Through Port-13 14:13', 'Midi Through:Midi Through Port-14 14:14', 'Midi Through:Midi Through Port-15 14:15', 'Midi Through:Midi Through Port-2 14:2', 'Midi Through:Midi Through Port-3 14:3', 'Midi Through:Midi Through Port-4 14:4', 'Midi Through:Midi Through Port-5 14:5', 'Midi Through:Midi Through Port-6 14:6', 'Midi Through:Midi Through Port-7 14:7', 'Midi Through:Midi Through Port-8 14:8', 'Midi Through:Midi Through Port-9 14:9', 'Terratec Aureon 7.1-Universe:ICE1724 MIDI 28:0', 'UM-1:UM-1 MIDI 1 36:0', 'UM-ONE:UM-ONE MIDI 1 40:0']
>>> c = connector.Connector()
>>> c.connect('MicroBrute:MicroBrute MIDI 1 44:0')
>>> c.get_sequence(6)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/MicroDude-1.3-py3.5.egg/microdude/connector.py", line 118, in get_sequence
  File "/usr/local/lib/python3.5/dist-packages/MicroDude-1.3-py3.5.egg/microdude/connector.py", line 133, in get_sequence_fragment
  File "/usr/local/lib/python3.5/dist-packages/MicroDude-1.3-py3.5.egg/microdude/connector.py", line 218, in rx_message
microdude.connector.ConnectorError: Connection error

```

Could you please help to troubleshoot this ? :)

I'm desperately trying to push some sequences to the microbrute on Linux.

Cheers
Erwan

**Comment by dagargo** [comment]
You opened the issue  #1 in which you finally get MicroDude to work.
Could you confirm this is still not working for you, please?

**Comment by erwan35** [comment]
Hello,

I was using Ubuntu 16.04 but now my system has been upgraded to 18.04 and I don't have this issue anymore.

Thanks for everything.

Cheers
Erwan

PS : FYI, this [wiki page](http://linuxmao.org/MicroDude)  has been written.

**Comment by dagargo** [comment]
Hi, Erwan.

Thanks for taking the time to test MicroDude. It's really nice to know this project is useful for others.

I'm closing the issue because it's probably due to dependency conflicts.

Cheers
